syntax = "proto3";

option java_package = "fun.witt.api.acl";
package fun.witt.api.acl;
option java_multiple_files = true;

option go_package = "../pb;pb";

import "common.proto";

service VideoService {
  rpc GetPublishVideoList(GetPublishVideoListRequest) returns (GetPublishVideoListResponse);
  rpc PublishVideo(PublishVideoRequest) returns (PublishVideoResponse);
  rpc GetFeedList(GetFeedListRequest) returns (GetFeedListResponse);
  rpc GetVideoInfoList(GetVideoInfoListReq) returns (GetVideoInfoListRsp);
  rpc GetFavoriteVideoList(GetFavoriteVideoListReq) returns (GetFavoriteVideoListRsp);
  rpc UpdateFavoriteCount(UpdateFavoriteCountReq) returns (UpdateFavoriteCountRsp);
  rpc UpdateCommentCount(UpdateCommentCountReq) returns (UpdateCommentCountRsp);
}

message UpdateFavoriteCountReq {
  int64 video_id = 1;
  int64 action_type = 2;
}

message UpdateFavoriteCountRsp {
  CommonResponse common_rsp = 1;
}

message UpdateCommentCountReq {
  int64 video_id = 1;
  int64 action_type = 2;
}

message UpdateCommentCountRsp {
  CommonResponse common_rsp = 1;
}

message GetFavoriteVideoListReq {
  int64 user_id = 1;
}

message GetFavoriteVideoListRsp {
  repeated VideoInfo video_list = 1;
}

message GetPublishVideoListRequest {
  int64 tokenUserId = 1;
  int64 userID = 2;
}

message GetPublishVideoListResponse {
  repeated VideoInfo video_list = 1;
}

message PublishVideoRequest {
  int64 userId = 1;
  string saveFile = 2;
  string title = 3;
}

message PublishVideoResponse {
}

message GetFeedListRequest {
  int64 currentTime = 1;
  int64 tokenUserId = 2;
}

message GetFeedListResponse {
  repeated VideoInfo video_list = 1;
  int64 nextTime = 2;
}

message VideoInfo {
  int64 id = 1;
  int64 author_id = 2;
  string play_url = 3;
  string cover_url = 4;
  int64 favorite_count = 5;
  int64 comment_count = 6;
  bool is_favorite = 7;
  string title = 8;
  int64 collect_count = 9;
  bool is_collect = 10;
}

message GetVideoInfoListReq {
  repeated int64 video_id = 1;
}

message GetVideoInfoListRsp {
  repeated VideoInfo video_info_list = 2;
}
